feat(quote-block) enable custom icons
Frontify/guideline-blocks pull request #341
Opened 2022-09-16 09:18 UTC by rawi96

2022-09-16 14:09 UTC, Walkeezy approved these changes

2022-09-21 14:16 UTC, celine-s reviewed
Overall: functionality is well implemented and works well. 👍 

The design has a few deviations from the figma file
- Size of the asset should be small. We don't have an assetInput which is size small yet. Needs adaptations in clarify, right?
- divider within dropdown missing: do we have that?
- when selected, the selected icon should itself be the dropdown. The way it is now is probably the easiest (and also a nice) way. Would check it again with Martin. wdyt?

One thought from my side: 
color cannot be adapted to the selected custom icon - do we want to remove the color input when the custom icon is selected? Or do you have another idea?

2022-09-21 14:27 UTC, celine-s reviewed
I extracted the quotation handling into a separate component. wdyt?

2022-09-29 07:33 UTC, SamuelAlev requested changes

2022-09-29 13:09 UTC, celine-s approved these changes

2022-09-29 13:21 UTC, SamuelAlev commented on packages/quote-block/src/Quotations.tsx
> +        )) || <>{children}</>
```suggestion
        )) : children
```

2022-09-29 13:22 UTC, SamuelAlev commented on packages/quote-block/src/Quotations.tsx
> +        (isQuotationMarkType && (
```suggestion
        (isQuotationMarkType ? (
```

2022-09-29 13:23 UTC, SamuelAlev commented on packages/quote-block/src/settings.tsx
> +                    show: (bundle: Bundle): boolean =>
```suggestion
                    show: (bundle) =>
```

2022-09-30 09:32 UTC, SamuelAlev approved these changes

2022-09-30 09:32 UTC, merged