fix: Template block pre-release improvements [CU-8692wq8w6]
Frontify/guideline-blocks pull request #699
Opened 2023-12-11 15:56 UTC by ruslan-sazonov

This PR introduces the following improvements to the template block:
- Block's responsiveness (layout)
- Added ability to remove the custom preview (if it's set) via the new preview's menu item
- Some minor UI/UX fixes and improvements

The full list of tackled issues in a [ClickUp Issue](https://app.clickup.com/t/8692wq8w6)

2023-12-15 09:29 UTC, mikeyrayvon commented on packages/template-block/src/components/types.ts
> +import { JSX } from 'react';
I have a PR open to export the type from brand-sdk rather than duplicating it in this file https://github.com/Frontify/brand-sdk/pull/652

2023-12-18 07:54 UTC, mikeyrayvon commented
Please don't merge until I've had a chance to work through it thoroughly, thanks!

2023-12-19 09:35 UTC, mikeyrayvon approved these changes

2023-12-20 10:00 UTC, ragi96 requested changes
Found that bug:

https://www.loom.com/share/8f5f40b5c8524714bb930f8eb8467598?sid=dc43ca12-3921-4f4e-845f-7b4fed47c5db

2023-12-20 10:35 UTC, ragi96 reviewed
Also if preview is set to `none`: 

The Upload Field is shown in edit mode, I don't think it should be shown then, as the template is already set

![Screenshot 2023-12-20 at 11 34 53](https://github.com/Frontify/guideline-blocks/assets/9362990/368ac89b-947c-45b9-afa2-2492f83cd97c)

2023-12-20 15:52 UTC, findmind commented
> Also if preview is set to `none`:
> 
> The Choose Template Field is shown in edit mode, I don't think it should be shown then, as the template is already set
> 
> ![Screenshot 2023-12-20 at 11 34 53](https://private-user-images.githubusercontent.com/9362990/291864262-368ac89b-947c-45b9-afa2-2492f83cd97c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODc4MDEsIm5iZiI6MTcwMzA4NzUwMSwicGF0aCI6Ii85MzYyOTkwLzI5MTg2NDI2Mi0zNjhhYzg5Yi05NDdjLTQ1YjktYWZhMi0yNDkyZjgzY2Q5N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTU1MTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJhNGE0OTYzZTA1YzgyNmI1Mjg4MGE1MGIyYmFhYzdmYWE4ZjJlZjNmM2ViNmU0YjkxYzgxNGMyZDkxY2ZmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MqfrscnsjSkeo96sZJ9gLp7E68Q-SBHz5yCS1ez8j1M)

This is actually the expected behaviour as designed; I also don't like it tbh. But this was already discussed. Thanks for the hint, though! 💪

2023-12-20 16:01 UTC, findmind commented
> Found that bug:
> 
> [loom.com/share/8f5f40b5c8524714bb930f8eb8467598?sid=dc43ca12-3921-4f4e-845f-7b4fed47c5db](https://www.loom.com/share/8f5f40b5c8524714bb930f8eb8467598?sid=dc43ca12-3921-4f4e-845f-7b4fed47c5db)

And also thanks, but that's actually also working as designed. I agree that the behaviour might as well be different, but it was agreed upon like that. We can adapt it if it turns out to be a problem.

2023-12-20 16:06 UTC, ragi96 commented
> > Found that bug:
> > [loom.com/share/8f5f40b5c8524714bb930f8eb8467598?sid=dc43ca12-3921-4f4e-845f-7b4fed47c5db](https://www.loom.com/share/8f5f40b5c8524714bb930f8eb8467598?sid=dc43ca12-3921-4f4e-845f-7b4fed47c5db)
> 
> And also thanks, but that's actually also working as designed. I agree that the behaviour might as well be different, but it was agreed upon like that. We can adapt it if it turns out to be a problem.

Ah okay, it's special, then probably thats also the reason for the `templateTextKey`

2023-12-20 16:11 UTC, findmind commented on packages/template-block/src/components/CustomButton.tsx
>      const screenReaderRef = useRef<HTMLDivElement>(null);
Removed the whole span, not needed. Bad copy-paste. ;-)

2023-12-20 16:17 UTC, ragi96 approved these changes
LGTM

2023-12-21 09:22 UTC, merged