feat: image block updates
Frontify/guideline-blocks pull request #738
Opened 2024-02-06 11:02 UTC by SamCreasey

CU-8693kyqyc

Initial design changes for the image block.

2024-02-09 11:57 UTC, ragi96 commented
merged so somebody gets assigned, sorry didn't had it in my mind

2024-02-14 08:10 UTC, utmishra requested changes
Hey @SamCreasey 
Visually, the changes look good 👍🏽 
There seems to be just one issue. Once I've set the alt text, I cannot remove it. If I delete the existing entry and save the alt text with blank text, I see that an empty `settings` payload is passed, thus the alt text is not updated.

2024-02-19 13:43 UTC, ragi96 commented on packages/image-block/src/ImageBlock.tsx
>      const blockId = appBridge.getBlockId().toString();
```suggestion
    const blockId = String(appBridge.context('blockId').get());
```

2024-02-19 13:43 UTC, ragi96 commented on packages/shared/src/components/EditAltTextFlyout/EditAltTextToolbarButton.tsx
> +/* (c) Copyright Frontify Ltd., all rights reserved. */
Would be cool to have this one tested

2024-02-20 05:42 UTC, SamCreasey commented on packages/shared/src/components/EditAltTextFlyout/EditAltTextToolbarButton.tsx
> +/* (c) Copyright Frontify Ltd., all rights reserved. */
fixed

2024-02-20 07:08 UTC, ragi96 approved these changes
Next time please in `vitest`, as we will migrate them anyway

2024-02-20 13:54 UTC, utmishra approved these changes
Looks good 👍🏽

2024-02-20 13:54 UTC, merged